name: "apkdiff"
description: "Signal-Android apkdiff script as a reusable action."
inputs:
  APKS_A:
    required: true
    description: "First set of APK files to compare."
  APKS_B:
    required: true
    description: "Second set of APK files to compare."
  IGNORE_FILES:
    required: false
    description: "List of files to ignore during comparison."

runs:
  using: composite
  steps:
    - name: Exclude some known different (but acceptable) files
      shell: bash
      run: |
        set -x
        mapfile -t files <<< "${{ inputs.IGNORE_FILES }}"
        for file in "${files[@]}"; do
          echo "<$file>"
        done
    - name: diff apks
      shell: bash
      run: |
        set -x
        mapfile -t apks_a <<< "${{ inputs.APKS_A }}"
        mapfile -t apks_b <<< "${{ inputs.APKS_B }}"
        for i in "${!apks_a[@]}"; do
          apk_a="${apks_a[$i]}"
          apk_b="${apks_b[$i]}"
          echo "Comparing $apk_a and $apk_b"
        done
