name: dev

on:
  push:

jobs:
  dev:
    runs-on: macos-26
    steps:
      - run: |
          set -x

          rm -rf /Applications/Xcode.app
          ditto /Applications/Xcode_26.2.app /Applications/Xcode.app
          rm -rf /Applications/Xcode_*
          echo DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer >> "$GITHUB_ENV"
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          xcrun metal --version

          xcodebuild --help || true

          sudo rm -rf /System/Library/AssetsV2/com_apple_MobileAsset_MetalToolchain/*.asset
          sudo rm -rf /private/var/run/com.apple.security.cryptexd/mnt/*
          curl -LO "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Xcode/MetalToolchain-17C48.exportedBundle.zip"
          unzip MetalToolchain-17C48.exportedBundle.zip
          xcodebuild -importComponent MetalToolchain -importPath ./MetalToolchain-17C48.exportedBundle

          xcodebuild -showComponent MetalToolchain

          ls -lsah /System/Library/AssetsV2/com_apple_MobileAsset_MetalToolchain/
          sleep 5
          ls -lsah /private/var/run/com.apple.security.cryptexd/mnt/
          sleep 5
          xcrun metal --version
