name: diff

on: push

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Download AppleStore IPA
        run: curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Signal-iOS/org.whispersystems.signal_8.14.decrypted.ipa" -o Signal-appstore.ipa
      - name: Download artifact from another workflow run
        uses: actions/download-artifact@v8
        with:
          name: applestore-build
          run-id: 27504935388
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: debug diff
        run: |
          set -x
          ls -lsah

          unzip -q Signal.ipa -d ./Signal
          unzip -q Signal-appstore.ipa -d ./org.whispersystems.signal_8.14.decrypted

          build="Signal/Payload/Signal.app/Frameworks/SignalServiceKit.framework/SignalServiceKit"
          official="org.whispersystems.signal_8.14.decrypted/Payload/Signal.app/Frameworks/SignalServiceKit.framework/SignalServiceKit"

          codesign --remove-signature $build
          codesign --remove-signature $official

          size -m $build > build.size
          size -m $official > official.size
          diff build.size official.size
          sleep 5


          otool -l $build > commands_local.txt
          otool -l $official > commands_officiel.txt
          diff commands_local.txt commands_officiel.txt || true
          sleep 5

          strings -a -n 8 $build > build.string
          strings -a -n 8 $official > official.string

          ls -lsah
          sleep 5

          diff build.string official.string || true
          sleep 5

      - name: Upload artifacts debug diff
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: |
            Signal/Payload/Signal.app/Frameworks/SignalServiceKit.framework/SignalServiceKit
            org.whispersystems.signal_8.14.decrypted/Payload/Signal.app/Frameworks/SignalServiceKit.framework/SignalServiceKit
