name: diff-ios-framework

on:
  workflow_dispatch:

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - name: Download AppleStore IPA
        run: curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-iOS/ph.telegra.Telegraph_12.9.decrypted.ipa" -o Telegram-appstore.ipa
      - name: Download artifact from another workflow run
        uses: actions/download-artifact@v8
        with:
          name: applestore-build
          run-id: 30257646794
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: debug diff
        run: |
          set -x
          ls -lsah

          unzip -q Telegram.ipa -d ./Telegram
          unzip -q Telegram-appstore.ipa -d ./ph.telegra.Telegraph_12.9.decrypted

          build="Telegram/Payload/Telegram.app/Frameworks/TelegramUIFramework.framework/TelegramUIFramework"
          official="ph.telegra.Telegraph_12.9.decrypted/Payload/Telegram.app/Frameworks/TelegramUIFramework.framework/TelegramUIFramework"

          codesign --remove-signature $build
          codesign --remove-signature $official

          python3 strip-uuid.py $build
          python3 strip-uuid.py $official

          sha256sum $build
          sha256sum $official

          size -m $build > build.size
          size -m $official > official.size
          diff build.size official.size || true
          sleep 5

          otool -l $build > commands_local.txt
          otool -l $official > commands_officiel.txt
          diff commands_local.txt commands_officiel.txt || true
          sleep 5

          strings -a -n 8 $build > build.string
          strings -a -n 8 $official > official.string
          diff build.string official.string || true
          sleep 5

          curl -sL "https://github.com/TelegramMessenger/Telegram-iOS/raw/refs/heads/master/tools/main.cpp" -o main.cpp
          clang main.cpp -lc++ -o telediff
          chmod +x telediff
          ./telediff $build $official

      - name: Upload artifacts debug diff
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: |
            Telegram/Payload/Telegram.app/Frameworks/TelegramServiceKit.framework/TelegramServiceKit
            ph.telegra.Telegraph_12.9.decrypted/Payload/Telegram.app/Frameworks/TelegramServiceKit.framework/TelegramServiceKit
