name: Signal-iOS

on: push

env:
  VERSION: 8.14.0.1637

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Download AppleStore IPA
        run: |
          export canonical_version=$(echo "${{ env.VERSION }}" | cut -d. -f1,2)
          curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Signal-iOS/org.whispersystems.signal_${canonical_version}.decrypted.ipa" -o Signal-appstore.ipa
      - name: build
        run: |
          set -x

          # Build in canonical path used by Signal
          id
          ls -lsah
          sudo mkdir -p /Volumes/workspace/
          sudo chown runner:staff /Volumes/workspace
          ls -lsah /Volumes/
          cd /Volumes/workspace/

          git clone --depth 1 --recurse-submodules https://github.com/signalapp/Signal-iOS -b "${{ env.VERSION }}" repository
          cd Signal-iOS
          make dependencies

          XCODE_VERSION=$(cat .xcode-version | cut -d' ' -f2)

          # Select the Xcode version used in .xcode-version
          echo DEVELOPER_DIR="/Applications/Xcode_${XCODE_VERSION}.app" >> "$GITHUB_ENV"
          sudo xcode-select -s /Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer

          Scripts/check_xcode_version.py --relaxed

          xcodebuild -downloadComponent MetalToolchain
          sleep 1

          xcodebuild -showComponent MetalToolchain && sleep 1 || true
          xcrun metal --version && sleep 1 || true
          xcodebuild -version && sleep 1 || true
          xcode-select -p && sleep 1 || true

          export NSUnbufferedIO=YES

          xcodebuild \
            -workspace Signal.xcworkspace \
            -scheme Signal \
            -disableAutomaticPackageResolution \
            -destination 'generic/platform=iOS' \
            CONFIGURATION_BUILD_DIR="/Volumes/workspace/repository/build" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -configuration "App Store Release" \
            DEPLOYMENT_POSTPROCESSING=YES \
            STRIP_INSTALLED_PRODUCT=YES \
            COPY_PHASE_STRIP=YES \
            CLANG_COVERAGE_MAPPING=NO \
            GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO \
            GCC_GENERATE_TEST_COVERAGE_FILES=NO \
            build

          # Manual Ad-Hoc sign
          cd /Volumes/workspace/repository/build
          if [ -d "Signal.app/Frameworks" ]; then
              for fwk in Signal.app/Frameworks/*.framework; do
                  if [ -d "$fwk" ]; then
                      codesign --force --sign - "$fwk"
                  fi
              done
          fi
          if [ -d "Signal.app/PlugIns" ]; then
              for appex in Signal.app/PlugIns/*.appex; do
                  if [ -d "$appex" ]; then
                      codesign --force --sign - "$appex"
                  fi
              done
          fi
          codesign --force --sign - Signal.app

          mkdir -p Payload
          cp -R Signal.app Payload/
          zip -qr Signal.ipa Payload/
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: /Volumes/workspace/repository/build/Signal.ipa
      - name: Verify reproducibility
        run: |
          git clone https://github.com/TelegramMessenger/Telegram-iOS --depth 1
          python Telegram-iOS/tools/ipadiff.py /Volumes/workspace/repository/build/Signal.ipa Signal-appstore.ipa
