name: Signal-iOS

on: push

env:
  VERSION: 8.14.0.1637

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Download AppleStore IPA
        run: curl -sL --fail "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-iOS/org.whispersystems.signal_${{ inputs.VERSION }}.decrypted.ipa" -o Signal-appstore.ipa
      - name: build
        run: |
          set -x

          cd /Users/Shared/

          git clone --depth 1 --recurse-submodules https://github.com/signalapp/Signal-iOS -b ${{ env.VERSION }}
          cd Signal-iOS
          make dependencies

          XCODE_VERSION=$(cat .xcode-version | cut -d' ' -f2)
          VERSION_CODE=$(echo "${{ env.VERSION }}" | awk -F. '{print $NF}')

          # Select the Xcode version used in .xcode-version
          echo DEVELOPER_DIR="/Applications/Xcode_${XCODE_VERSION}.app" >> "$GITHUB_ENV"
          sudo xcode-select -s /Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer

          Scripts/check_xcode_version.py --relaxed

          xcodebuild -downloadComponent MetalToolchain
          sleep 1

          xcodebuild -showComponent MetalToolchain && sleep 1 || true
          xcrun metal --version && sleep 1 || true
          xcodebuild -version && sleep 1 || true
          xcode-select -p && sleep 1 || true

          export NSUnbufferedIO=YES

          xcodebuild \
            -workspace Signal.xcworkspace \
            -scheme Signal \
            -disableAutomaticPackageResolution \
            -destination 'generic/platform=iOS' \
            CONFIGURATION_BUILD_DIR="/Users/Shared/Signal-iOS/build" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -configuration "App Store Release" \
            DEPLOYMENT_POSTPROCESSING=YES \
            STRIP_INSTALLED_PRODUCT=YES \
            COPY_PHASE_STRIP=YES \
            build

          cd /Users/Shared/Signal-iOS/build
          codesign --force --deep --sign - Signal.app

          mkdir -p Payload
          cp -R Signal.app Payload/
          zip -qr Signal.ipa Payload/
      - name: debug
        run: |
          set -x
          ls -lsah /Users/Shared/Signal-iOS/build
          sleep 2
          ls -lsah /Users/Shared/Signal-iOS/build/Signal.app
          sleep 2
          ls -lsah /Users/Shared/Signal-iOS/build/Payload || true
          sleep 2
          find /Users/Shared/ -name "*.ipa"
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: applestore-build
          path: /Users/Shared/Signal-iOS/build/Signal.ipa
      - name: Verify reproducibility
        run: |
          git clone https://github.com/TelegramMessenger/Telegram-iOS --depth 1
          python Telegram-iOS/tools/ipadiff.py /Users/Shared/Signal-iOS/build/Signal.ipa Signal-appstore.ipa
