name: Telegram-iOS

on:
  push:

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: Install mitmproxy
        run: |
          sleep 1
          xcodes list
          sleep 1
          xcodes installed
          sleep 1

          ls -lsah /Applications/
