name: Telegram-iOS

on:
  push:

jobs:
  applestore-verify:
    runs-on: macos-26
    steps:
      - name: build
        run: |
          set -x

          hdiutil attach /System/Library/AssetsV2/com_apple_MobileAsset_MetalToolchain/058e1b31129b642e40598a87b55aa54b2a29e538.asset/AssetData/Restore/022-21521-014.dmg -mountpoint /tmp/metal_tc -nobrowse -quiet

          find /tmp/metal_tc -name "metal" -type f | head -1 | xargs -I{} {} --version
