name: Telegram-Android

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "VERSION"
        required: true

run-name: "Check ${{ github.workflow }} v${{ inputs.VERSION }} reproducibility"

env:
  SIGNATURE_SHA256: 49c1522548ebacd46ce322b6fd47f6092bb745d0f88082145caf35e14dcc38e1

jobs:
  website-download:
    runs-on: ubuntu-latest
    steps:
      - name: aapt
        run: echo "PATH=$PATH:/usr/local/lib/android/sdk/build-tools/37.0.0" >> $GITHUB_ENV
      - name: Download
        id: download
        run: |
          curl -L "https://github.com/BarbossHack/reproducible-LFS/raw/refs/heads/master/Telegram-Android/${{ inputs.VERSION }}.apk" -o Telegram-website.apk
          AAPT_BADGING=$(aapt dump badging Telegram-website.apk)
          VERSION_NAME=$(echo "$AAPT_BADGING" | grep -o "versionName='[^']*'" | cut -d"'" -f2)
          VERSION_CODE=$(echo "$AAPT_BADGING" | grep -o "versionCode='[^']*'" | cut -d"'" -f2)
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_OUTPUT
          if [ "$VERSION_NAME" != "${{ inputs.VERSION }}" ]; then
            echo "Version name mismatch: expected ${{ inputs.VERSION }}, got $VERSION_NAME"
            exit 1
          fi
          apksigner verify -v --print-certs Telegram-website.apk | grep $SIGNATURE_SHA256
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: website-official
          path: Telegram-website.apk
    outputs:
      VERSION_CODE: ${{ steps.download.outputs.VERSION_CODE }}

  playstore-download:
    runs-on: ubuntu-latest
    needs: [website-download]
    steps:
      - uses: actions/checkout@v6
      - name: aapt
        run: echo "PATH=$PATH:/usr/local/lib/android/sdk/build-tools/37.0.0" >> $GITHUB_ENV
      - name: Download
        run: |
          VERSION_CODE="${{ needs.website-download.outputs.VERSION_CODE }}"
          VERSION_CODE_PLAYSTORE=$(( ($VERSION_CODE / 10) * 10 + 1 ))
          echo "Using version code $VERSION_CODE_PLAYSTORE for playstore download, expected to be $VERSION_CODE / 10 * 10 + 1"

          cargo build --manifest-path gpapi/Cargo.toml --release
          gpapi/target/release/gpapi --email "${{ secrets.EMAIL }}" --aas-token "${{ secrets.AAS_TOKEN }}" --package "org.telegram.messenger" --version-code ${VERSION_CODE_PLAYSTORE} --output=./playstore-official/ --download

          AAPT_BADGING=$(aapt dump badging playstore-official/org.telegram.messenger/org.telegram.messenger.apk)
          PLAYSTORE_VERSION=$(echo "$AAPT_BADGING" | grep -o "versionName='[^']*'" | cut -d"'" -f2)
          if [[ "${{ inputs.VERSION }}" == "$PLAYSTORE_VERSION" ]]; then
            echo "✅ Versions $PLAYSTORE_VERSION match"
          else
            echo "❌ Versions differ: expected ${{ inputs.VERSION }} but got $PLAYSTORE_VERSION"
            exit 1
          fi
          apksigner verify -v --print-certs playstore-official/org.telegram.messenger/org.telegram.messenger.apk | grep $SIGNATURE_SHA256
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: playstore-official
          path: playstore-official/

  build:
    runs-on: ubuntu-latest
    needs: [website-download, playstore-download]
    steps:
      - name: Free up disk space
        uses: BarbossHack/reproducible/.github/actions/free-up-github-action@master
      - name: Build
        run: |
          git clone https://github.com/DrKLO/Telegram
          cd Telegram
          git checkout $(git log --all --grep="${{ inputs.VERSION }}" -n 1 --format="%H")
          git submodule update --init --recursive --depth=1
          docker build -t telegram-build .
          docker run --rm -v "$PWD":/home/gradle:Z -w /home/gradle telegram-build gradle -Dorg.gradle.jvmargs="-Xmx8g" :TMessagesProj_AppStandalone:assembleAfatStandalone :TMessagesProj_App:bundleBundleAfatRelease

          sudo chown -R $(id -u):$(id -g) .
          mv TMessagesProj_App/build/outputs/bundle/bundleAfatRelease/TMessagesProj_App-bundleAfat-release.aab ../Telegram-build-bundle.aab
          mv TMessagesProj_AppStandalone/build/outputs/apk/afat/standalone/app.apk ../Telegram-build-website.apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: |
            Telegram-build-website.apk
            Telegram-build-bundle.aab

  website-verify:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
      - uses: BarbossHack/reproducible/.github/actions/apkdiff@master
        with:
          APKS_A: build/Telegram-build-website.apk
          APKS_B: website-official/Telegram-website.apk
          IGNORE_FILES: |-
            META-INF/CERT.RSA
            META-INF/CERT.SF
            META-INF/BNDLTOOL.RSA
            META-INF/BNDLTOOL.SF
      - name: apkdiff
        run: |
          curl https://raw.githubusercontent.com/DrKLO/Telegram/refs/heads/master/apkdiff.py -o apkdiff.py
          output=$(python apkdiff.py website-official/Telegram-website.apk build/Telegram-build-website.apk)
          echo "$output"
          echo "$output" | grep -F "APKs are the same"

  playstore-verify:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
      - name: aapt
        run: echo "PATH=$PATH:/usr/local/lib/android/sdk/build-tools/37.0.0" >> $GITHUB_ENV
      - name: apkfrombundle
        continue-on-error: true
        run: |
          curl https://raw.githubusercontent.com/DrKLO/Telegram/refs/heads/master/apkfrombundle.py -o apkfrombundle.py
          output=$(python apkfrombundle.py build/Telegram-build-bundle.aab playstore-official/org.telegram.messenger/org.telegram.messenger.apk)
          echo "$output"
          echo "$output" | grep -F "APKs are the same"
      - name: Aab to Apk
        run: |
          curl -L https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar -o bundletool.jar
          java -jar bundletool.jar build-apks --bundle=./build/Telegram-build-bundle.aab --output-format=DIRECTORY --output=apks
      - name: Exclude some known different (but acceptable) files
        run: |
          zip -d playstore-official/org.telegram.messenger/org.telegram.messenger.apk "META-INF/CERT.RSA" "META-INF/CERT.SF" "META-INF/BNDLTOOL.RSA" "META-INF/BNDLTOOL.SF"
          zip -d apks/splits/base-master.apk "META-INF/CERT.RSA" "META-INF/CERT.SF" "META-INF/BNDLTOOL.RSA" "META-INF/BNDLTOOL.SF"
      - name: Signal Apkdiff
        run: |
          pip install uv
          git clone https://github.com/BarbossHack/Signal-Android -b reproducible-refactor-axml-diff --depth 1 apkdiff
          cd apkdiff/reproducible-builds/apkdiff
          uv sync
          base_output=$(uv run apkdiff.py ../../../playstore-official/org.telegram.messenger/org.telegram.messenger.apk ../../../apks/splits/base-master.apk 2>&1 || true)
          echo "$base_output"
          uv run apkdiff.py ../../../playstore-official/org.telegram.messenger/org.telegram.messenger.config.arm64_v8a.apk ../../../apks/splits/base-arm64_v8a.apk
          uv run apkdiff.py ../../../playstore-official/org.telegram.messenger/org.telegram.messenger.config.en.apk ../../../apks/splits/base-en.apk
          uv run apkdiff.py ../../../playstore-official/org.telegram.messenger/org.telegram.messenger.config.xxhdpi.apk ../../../apks/splits/base-xxhdpi.apk

          find mismatches/ -type f -exec sha256sum {} \;

          not_in_second=$(awk 'NR==FNR{h[$1]++;next} !($1 in h){print}' <(find "mismatches/second/" -type f -exec sha256sum {} + | sort -k1) <(find "mismatches/first/" -type f -exec sha256sum {} + | sort -k1))
          not_in_first=$(awk 'NR==FNR{h[$1]++;next} !($1 in h){print}' <(find "mismatches/first/" -type f -exec sha256sum {} + | sort -k1) <(find "mismatches/second/" -type f -exec sha256sum {} + | sort -k1))

          echo "Result:"
          echo "Files in playstore but not in build:"
          echo "$not_in_second"
          echo "Files in build but not in playstore:"
          echo "$not_in_first"

          if [[ $(echo "$not_in_second" | wc -l) -gt 0 ]] || [[ $(echo "$not_in_first" | wc -l) -gt 0 ]] || [[ "$base_output" == *"Manifest lengths differ"* ]];
          then
            exit 1
          fi

  notify:
    needs: [build, website-verify, playstore-verify]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: BarbossHack/reproducible/.github/actions/discord-webhook@master
        with:
          VERSION: ${{ inputs.VERSION }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          needs: ${{ toJSON(needs) }}
